---
apiVersion: v1
kind: Pod
metadata:
  name: k8slivenesschweck
spec:
  containers:
  - name: app_deployment
    image: nagesh250/k8s:1.0
    ports:
      - name: http
        containerPort: 8082
        protocol: TCP
    envFrom:
       - configMapRef:
          name: player-posix-demo